export const PERMISSIONS = {
  // Test Management
  TEST: {
    CREATE: 'TEST.CREATE',
    READ: 'TEST.READ',
    UPDATE: 'TEST.UPDATE',
    DELETE: 'TEST.DELETE',
  },

  TEST_RUN: {
    CREATE: 'TEST_RUN.CREATE',
    READ: 'TEST_RUN.READ',
    EXECUTE: 'TEST_RUN.EXECUTE',
    CANCEL: 'TEST_RUN.CANCEL',
    DELETE: 'TEST_RUN.DELETE',
  },

  // Call Management
  IMPORTED_CALL: {
    IMPORT: 'IMPORTED_CALL.IMPORT',
    READ: 'IMPORTED_CALL.READ',
    ANALYZE: 'IMPORTED_CALL.ANALYZE',
    DELETE: 'IMPORTED_CALL.DELETE',
  },

  // Speech Services
  SPEECH: {
    TRANSCRIBE: 'SPEECH.TRANSCRIBE',
    SYNTHESIZE: 'SPEECH.SYNTHESIZE',
    READ: 'SPEECH.READ',
  },

  // Digital Human
  DIGITAL_HUMAN: {
    CONFIGURE: 'DIGITAL_HUMAN.CONFIGURE',
    READ: 'DIGITAL_HUMAN.READ',
    UPDATE: 'DIGITAL_HUMAN.UPDATE',
  },

  // Telephony
  TELEPHONY: {
    INITIATE: 'TELEPHONY.INITIATE',
    READ: 'TELEPHONY.READ',
    CONFIGURE: 'TELEPHONY.CONFIGURE',
  },

  // Organization Management
  ORGANIZATION: {
    CREATE: 'ORGANIZATION.CREATE',
    READ: 'ORGANIZATION.READ',
    UPDATE: 'ORGANIZATION.UPDATE',
    DELETE: 'ORGANIZATION.DELETE',
  },

  // User Management
  USER: {
    CREATE: 'USER.CREATE',
    READ: 'USER.READ',
    UPDATE: 'USER.UPDATE',
    DELETE: 'USER.DELETE',
  },

  // Role Management
  ROLE: {
    CREATE: 'ROLE.CREATE',
    READ: 'ROLE.READ',
    UPDATE: 'ROLE.UPDATE',
    DELETE: 'ROLE.DELETE',
  },

  // Permission Management
  PERMISSION: {
    READ: 'PERMISSION.READ',
  },

  // System
  ANALYTICS: {
    READ: 'ANALYTICS.READ',
    EXPORT: 'ANALYTICS.EXPORT',
  },

  SETTINGS: {
    READ: 'SETTINGS.READ',
    UPDATE: 'SETTINGS.UPDATE',
  },

  AUDIT_LOG: {
    READ: 'AUDIT_LOG.READ',
    EXPORT: 'AUDIT_LOG.EXPORT',
  },
} as const;

export const ALL_PERMISSIONS = Object.values(PERMISSIONS)
  .map(resource => Object.values(resource))
  .flat();