export const PERMISSIONS = {
  // Job Management
  JOB_REQUEST: {
    CREATE: 'JOB_REQUEST.CREATE',
    READ: 'JOB_REQUEST.READ',
    UPDATE: 'JOB_REQUEST.UPDATE',
    DELETE: 'JOB_REQUEST.DELETE',
  },

  OFFER: {
    CREATE: 'OFFER.CREATE',
    READ: 'OFFER.READ',
    UPDATE: 'OFFER.UPDATE',
    DELETE: 'OFFER.DELETE',
    APPROVE: 'OFFER.APPROVE',
    REJECT: 'OFFER.REJECT',
  },

  CONTRACT: {
    CREATE: 'CONTRACT.CREATE',
    READ: 'CONTRACT.READ',
    UPDATE: 'CONTRACT.UPDATE',
    DELETE: 'CONTRACT.DELETE',
    SIGN: 'CONTRACT.SIGN',
  },

  // Worker Management
  WORKER: {
    CREATE: 'WORKER.CREATE',
    READ: 'WORKER.READ',
    UPDATE: 'WORKER.UPDATE',
    DELETE: 'WORKER.DELETE',
    ASSIGN: 'WORKER.ASSIGN',
  },

  TIMESHEET: {
    CREATE: 'TIMESHEET.CREATE',
    READ: 'TIMESHEET.READ',
    UPDATE: 'TIMESHEET.UPDATE',
    DELETE: 'TIMESHEET.DELETE',
    APPROVE: 'TIMESHEET.APPROVE',
    REJECT: 'TIMESHEET.REJECT',
  },

  // Financial
  INVOICE: {
    CREATE: 'INVOICE.CREATE',
    READ: 'INVOICE.READ',
    UPDATE: 'INVOICE.UPDATE',
    DELETE: 'INVOICE.DELETE',
    APPROVE: 'INVOICE.APPROVE',
  },

  PAYMENT: {
    CREATE: 'PAYMENT.CREATE',
    READ: 'PAYMENT.READ',
    UPDATE: 'PAYMENT.UPDATE',
    DELETE: 'PAYMENT.DELETE',
  },

  // Organization
  ORGANIZATION: {
    CREATE: 'ORGANIZATION.CREATE',
    READ: 'ORGANIZATION.READ',
    UPDATE: 'ORGANIZATION.UPDATE',
    DELETE: 'ORGANIZATION.DELETE',
  },

  USER: {
    CREATE: 'USER.CREATE',
    READ: 'USER.READ',
    UPDATE: 'USER.UPDATE',
    DELETE: 'USER.DELETE',
  },

  ROLE: {
    CREATE: 'ROLE.CREATE',
    READ: 'ROLE.READ',
    UPDATE: 'ROLE.UPDATE',
    DELETE: 'ROLE.DELETE',
  },

  PERMISSION: {
    CREATE: 'PERMISSION.CREATE',
    READ: 'PERMISSION.READ',
    UPDATE: 'PERMISSION.UPDATE',
    DELETE: 'PERMISSION.DELETE',
  },

  // System
  ANALYTICS: {
    READ: 'ANALYTICS.READ',
    EXPORT: 'ANALYTICS.EXPORT',
  },

  SETTINGS: {
    READ: 'SETTINGS.READ',
    UPDATE: 'SETTINGS.UPDATE',
  },

  AUDIT_LOG: {
    READ: 'AUDIT_LOG.READ',
    EXPORT: 'AUDIT_LOG.EXPORT',
  },
} as const;

export const ALL_PERMISSIONS = Object.values(PERMISSIONS)
  .map(resource => Object.values(resource))
  .flat();